== Link relations

=== General

This clause defines a number of new link relations required to
facilitate subscription upgrades.

[[la-subscribe-caldav]]
=== subscribe-caldav

This specifies an access point which is a full implementation of
caldav but requires no authentication. The end point allows the full
range of reports as defined by the CalDAV specification.

The client MUST follow the specification to determine exactly what
operations are allowed on the access point - for example to determine
if DAV:sync-collection is supported.

The URL MAY include some form of token to allow write access to the
targeted collection. The client must check its permissions to
determine whether it has been granted write access.


[[la-subscribe-caldav-auth]]
=== subscribe-caldav-auth


This specifies an access point which is a full implementation of
caldav and requires authentication. This may allow read-write access
to the resource.

The client MUST follow the specification to determine exactly what
operations are allowed on the access point -- for example to determine
if DAV:sync-collection is supported.


[[la-subscribe-webdav-sync]]
=== subscribe-webdav-sync

This specifies an access point which supports only <<RFC6578>> (WebDAV sync).

This allows the client to issue a DAV:sync-collection report on the resource to
obtain updates.

The client MUST follow the requirements of <<RFC6578>>.


[[la-subscribe-enhanced-get]]
=== subscribe-enhanced-get

This specifies an access point which supports the enhanced GET protocol
defined in <<enhanced-get>>.

The client and server MUST follow the protocol as defined in <<enhanced-get>>.

