
[#iana]
== IANA Considerations


=== Sync-Token HTTP Header Field Registration

This specification updates the "Message Headers" registry entry for "Sync-Token" in <<RFC3864>> to refer to this document.

[source]
----
   Header Field Name: Sync-Token
   Protocol: http
   Status: standard
   Reference: <this-document>
----

=== Preference Registrations

The following preferences have been added to the HTTP Preferences
Registry defined in <<RFC7240>>

Preference::  subscribe-enhanced-get

Value::  None.

Description::  Marks the interaction as enhanced get and provides the
optional sync-token and page size.

Reference:: this document

Preference::  limit

Value:: An integer page size.

Description::  Provide a limit on the number of components in the response.

Reference:: this document

=== Link Relation Registrations

The following link relation values have been added to
the Reference Types Registry defined in <<RFC8288,section=6.2.2>>:

[cols="a,a,a",options=header]
|===
| Relation Name          | Description | Reference

| subscribe-caldav       | Current     | <<la-subscribe-caldav>>
| subscribe-caldav_auth  | Current     | <<la-subscribe-caldav-auth>>
| subscribe-webdav-sync  | Current     | <<la-subscribe-webdav-sync>>
| subscribe-enhanced_get | Current     | <<la-subscribe-enhanced-get>>

|===

=== New and updated iCalendar Elements Registration

This specification updates <<RFC5545>> by adding and updating
a number of elements according to the procedures and templates specified in
<<RFC5545, section=8.2>>.

==== Initialization of the Status registry

This specification updates <<RFC5545>> by adding a Status value registry to the iCalendar Elements registry
located here: <https://www.iana.org/assignments/icalendar> and initializing it as per <<RFC5545>>.

located here: <hello>.

.Initial Status Value Registry
[cols="a,a,a",options=header]
|===
| Name          | Status | Reference

| CANCELLED    | Current | <<RFC5545, section=3.8.1.11>>
| COMPLETED    | Current | <<RFC5545, section=3.8.1.11>>
| CONFIRMED    | Current | <<RFC5545, section=3.8.1.11>>
| DRAFT        | Current | <<RFC5545, section=3.8.1.11>>
| FINAL        | Current | <<RFC5545, section=3.8.1.11>>
| IN-PROCESS   | Current | <<RFC5545, section=3.8.1.11>>
| NEEDS-ACTION | Current | <<RFC5545, section=3.8.1.11>>
| TENTATIVE    | Current | <<RFC5545, section=3.8.1.11>>

|===

==== Update of the Status registry

This specification further updates the Status registry with the
additional DELETED value defined in this document.

.Updated Status Value Registry
[cols="a,a,a",options=header]
|===
| Value    | Status  | Reference

| DELETED   | Current | This Spec, <<enhanced-get-deletion>>

|===
