
[#iana]
== IANA Considerations


=== Sync-Token HTTP Header Field Registration

This specification updates the "Message Headers" registry entry for "Sync-Token" in <<RFC3864>> to refer to this document.

   Header Field Name: Sync-Token
   Protocol: http
   Status: standard
   Reference: <this-document>

=== Preference Registrations

The following preferences have been added to the HTTP Preferences
Registry defined in <<RFC7240>>

Preference::  subscribe-enhanced-get

Value::  None.

Description::  Marks the interaction as enhanced get and provides the
optional sync-token and page size.

Reference:: this document

Preference::  limit

Value:: An integer page size.

Description::  Provide a limit on the number of components in the response.

Reference:: this document

=== Link Relation Registrations

The following link relation values have been added to
the Reference Types Registry defined in <<RFC8288,section=6.2.2>>:

[cols="a,a,a",options=header]
|===
| Relation Name          | Description | Reference

| subscribe-caldav       | Current     | <<la-subscribe-caldav>>
| subscribe-caldav_auth  | Current     | <<la-subscribe-caldav-auth>>
| subscribe-webdav-sync  | Current     | <<la-subscribe-webdav-sync>>
| subscribe-enhanced_get | Current     | <<la-subscribe-enhanced-get>>

|===
